' This file is automatically generated from Podman Desktop preferences.
set FSO = CreateObject("Scripting.FileSystemObject")
Set WshShell = CreateObject("WScript.Shell")
if FSO.FileExists("C:\Users\zhuxx\AppData\local\Programs\podman-desktop\Podman Desktop.exe") then
  WshShell.CurrentDirectory = "C:\Users\zhuxx\AppData\local\Programs\podman-desktop"
  WshShell.Run chr(34) & "C:\Users\zhuxx\AppData\local\Programs\podman-desktop\Podman Desktop.exe" & Chr(34), 0
end if  
Set WshShell = Nothing
